site_name: PFHelper Documentation Page
nav:
    - Home: index.md
    - About: about.md
    - ColorsHelper: colorsHelper.md
    - MathsHelper: mathsHelper.md
    - ObjectRegister: objectRegister.md
    - AnimationsHelper: animationHelper.md
    - ObjectPositioner: objectPositioner.md
    - ResizeManager: resizeManager.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - '../stylesheets/extra.css'
