site_name: PFHelper Documentation Page
nav:
    - Home: index.md
    - MathsHelper: mathsHelper.md
    - ObjectRegister: objectRegister.md
    - ResizeManager: resizeManager.md
    - About: about.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite
  - admonition